name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  intl: ^0.20.2
  shared_preferences: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
